/* ============ TERRAR U — shared product catalog ============ */
const CATALOG = [
  {
    id: "bottled-grove",
    name: "The Bottled Grove",
    kind: "Corked bottle ecosystem",
    price: 259,
    img: "assets/products/p1.webp",
    badge: "Limited",
    size: "Medium",
    shape: "Cylinder",
    customizable: true,
    rating: 4.8,
    reviews: 24,
    desc: "A whole grove folded into a vintage corked bottle. Twisted driftwood climbs past maidenhair ferns and wild mycena mushrooms, rooted in layered stone and living soil. Sealed once, alive for decades.",
  },
  {
    id: "bloom-orb",
    name: "Bloom Orb",
    kind: "Wildflower meadow sphere",
    price: 289,
    img: "assets/products/p2.webp",
    badge: "Bestseller",
    size: "Medium",
    shape: "Globe",
    customizable: true,
    rating: 4.9,
    reviews: 41,
    desc: "A hand-blown glass sphere holding a miniature alpine meadow — daisies, forget-me-nots and mountain bells around a sculptural branch. Our most loved piece, and the brightest world we make.",
  },
  {
    id: "terra-cube",
    name: "Terra Cube",
    kind: "Square glass forest",
    price: 229,
    img: "assets/products/p3.webp",
    badge: "New",
    size: "Small",
    shape: "Geometric",
    customizable: true,
    rating: 4.7,
    reviews: 12,
    desc: "Clean lines, wild interior. A precision glass cube with a cork canopy, planted with ferns, cushion moss and a bonsai-grade driftwood spine. Made for desks, shelves and quiet corners.",
  },
  {
    id: "fern-column",
    name: "The Fern Column",
    kind: "Tall sealed jar · Cork lid",
    price: 219,
    img: "assets/products/p4.webp",
    badge: null,
    size: "Large",
    shape: "Jar",
    customizable: true,
    rating: 4.6,
    reviews: 18,
    desc: "A tall corked column where bird's-nest ferns and creeping fig climb a driftwood trunk. Vertical, sculptural, and fully self-sustaining — a statement piece for floors and consoles.",
  },
  {
    id: "arid-glass",
    name: "Arid Glass",
    kind: "Open succulent terrarium",
    price: 139,
    img: "assets/products/p5.webp",
    badge: null,
    size: "Small",
    shape: "Cylinder",
    customizable: false,
    rating: 4.5,
    reviews: 9,
    desc: "An open desert in a clear cylinder — haworthia, echeveria and stone-crop over mineral gravel. The easiest world to keep: bright light, a sip of water a month, nothing more.",
  },
];

function findProduct(id) {
  return CATALOG.find((p) => p.id === id) || CATALOG[0];
}
